# Generated by Django 3.0.7 on 2020-07-05 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(db_index=True, max_length=150, verbose_name='Категория')),
                ('page_adress', models.SlugField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category_title'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_title', models.CharField(db_index=True, max_length=150, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['theme_title'],
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, verbose_name='Адрес страницы')),
                ('course_slug', models.CharField(blank=True, max_length=50, verbose_name='Адрес курса')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('preview_content', models.TextField(blank=True, verbose_name='Текст превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('icon', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Иконка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.Category', verbose_name='Категория')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.Theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['created_at'],
            },
        ),
    ]
