# Generated by Django 3.0.7 on 2020-07-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_theme_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Слаг темы'),
        ),
    ]
