# Generated by Django 3.0.7 on 2020-07-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_theme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='theme_slug',
            field=models.CharField(blank=True, max_length=50, verbose_name='Адрес темы'),
        ),
    ]
