# Generated by Django 3.0.7 on 2020-08-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lessons_theme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_preview_content',
            field=models.TextField(blank=True, verbose_name='Текст превью'),
        ),
    ]
