# Generated by Django 3.0.7 on 2020-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20200801_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_age',
            field=models.CharField(blank=True, max_length=150, verbose_name='Возраст'),
        ),
    ]
